### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by bucketclone** [dzikoysk/pandomium#2] opened 2017-04-22 18:34 UTC
I think adding support for macOS is now the most important thing for the Pandomium project. JCEF wrapper can be done later.

**Comment by zmlctt** [comment] 2018-06-29 11:13
is it now support macOS?

**Comment by dzikoysk** [comment] 2018-07-03 16:40
I don't have macOS so I can't build natives. You can try to follow these steps:
@zmlctt https://github.com/dzikoysk/Pandomium/wiki/macOS-Build

**Comment by zmlctt** [comment] 2018-07-04 04:58
thanks, I tried but failed，look forward to support mac.

**Comment by Peng-YM** [comment] 2018-08-07 03:32
I'm trying to compile mac os x native using ninja, here's the output:
```
> cmake -G "Ninja" -DPROJECT_ARCH="x86_64" -DCMAKE_BUILD_TYPE=Release ..
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_NO_UNDEFINED_VAR_TEMPLATE
-- Performing Test COMPILER_SUPPORTS_NO_UNDEFINED_VAR_TEMPLATE - Success
-- Found PythonInterp: /usr/local/bin/python (found version "2.7.15")
-- Found JNI: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/libjawt.dylib (Required is at least version "1.7")
-- Found Java: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/bin/java (found suitable version "1.8.0.152", minimum required is "1.7") found components:  Development
-- Generating native/jcef_version.h file...
File native/jcef_version.h is already up to date.
-- Downloading clang-format from Google Storage...
0> File tools/buildtools/mac/clang-format exists and SHA1 matches. Skipping.
Success!
Downloading 1 files took 0.008311 second(s)
-- *** CEF CONFIGURATION SETTINGS ***
-- Generator:                    Ninja
-- Platform:                     Darwin
-- Project architecture:         x86_64
-- Build type:                   Release
-- Binary distribution root:     /Users/pengym/JCEF67/src/third_party/cef/cef_binary_3.3396.1775.g5340bb0_macosx64
-- Base SDK:
-- Target SDK:                   10.9
-- Standard libraries:           -lpthread;-framework Cocoa;-framework AppKit
-- Compile defines:              __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS
-- Compile defines (Debug):
-- Compile defines (Release):
-- C compile flags:              -fno-strict-aliasing;-fstack-protector;-funwind-tables;-fvisibility=hidden;-Wall;-Werror;-Wextra;-Wendif-labels;-Wnewline-eof;-Wno-missing-field-initializers;-Wno-unused-parameter;-mmacosx-version-min=10.9 -std=c99
-- C compile flags (Debug):      -O0;-g
-- C compile flags (Release):    -O3
-- C++ compile flags:            -fno-strict-aliasing;-fstack-protector;-funwind-tables;-fvisibility=hidden;-Wall;-Werror;-Wextra;-Wendif-labels;-Wnewline-eof;-Wno-missing-field-initializers;-Wno-unused-parameter;-mmacosx-version-min=10.9 -fno-exceptions;-fno-rtti;-fno-threadsafe-statics;-fobjc-call-cxx-cdtors;-fvisibility-inlines-hidden;-std=gnu++11;-Wno-narrowing;-Wsign-compare;-Wno-undefined-var-template
-- C++ compile flags (Debug):    -O0;-g
-- C++ compile flags (Release):  -O3
-- Exe link flags:               -Wl,-search_paths_first;-Wl,-ObjC;-Wl,-pie
-- Exe link flags (Debug):
-- Exe link flags (Release):     -Wl,-dead_strip
-- Shared link flags:            -Wl,-search_paths_first;-Wl,-ObjC;-Wl,-pie
-- Shared link flags (Debug):
-- Shared link flags (Release):  -Wl,-dead_strip
-- *** JCEF CONFIGURATION SETTINGS ***
-- Python executable:            /usr/local/bin/python
-- Java directory:               /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home
-- JNI libraries:                /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/libjawt.dylib;/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre/lib/server/libjvm.dylib
-- JNI include directories:      /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/include;/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/include/darwin;/Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/include
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pengym/JCEF67/src/jcef_build
```

```
> ninja -j4
[166/238] Linking CXX static library libcef_dll_wrapper/libcef_dll_wrapper.a
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(cef_atomicops_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(cef_lock.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(libcef_dll_wrapper2.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(cef_atomicops_x86_gcc.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(cef_lock.cc.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: libcef_dll_wrapper/libcef_dll_wrapper.a(libcef_dll_wrapper2.cc.o) has no symbols
[238/238] Linking CXX shared library native/Release/libjcef.dylib
ld: warning: -pie being ignored. It is only used when linking a main executable
Buildfile: /Users/pengym/JCEF67/src/build.xml

compile:
    [javac] Compiling 148 source files to /Users/pengym/JCEF67/src/jcef_build/native/Release
     [copy] Copying 1446 files to /Users/pengym/JCEF67/src/jcef_build/native/Release

jar:
      [jar] Building jar: /Users/pengym/JCEF67/src/jcef_build/native/Release/jcef.jar
      [jar] Building jar: /Users/pengym/JCEF67/src/jcef_build/native/Release/jcef-tests.jar

bundle:
[bundleapp] Creating app bundle: jcef_app

BUILD SUCCESSFUL
Total time: 4 seconds
```
Looks ok but when I open `jcef_app.app`, an error occurs:
```
> open jcef_app.app
LSOpenURLsWithRole() failed with error -10810 for the file /Users/pengym/JCEF67/src/jcef_build/native/Release/jcef_app.app.
```

**Comment by dzikoysk** [comment] 2018-08-07 09:10
https://apple.stackexchange.com/questions/181026/lsopenurlswithrole-failed-with-error-10810-cant-open-install-os-x-yosemite

Is your jcef_app.app executable?

**Comment by Peng-YM** [comment] 2018-08-08 01:01
I already set it to executable with `chmod +x jcef_app.app`

**Comment by Peng-YM** [comment] 2018-08-08 01:07
I found something weird when I look at the java source code built by CMake. Many file end with a sequence of `e`, any help? 
![](https://ws1.sinaimg.cn/large/c2dfc71dgy1fu20pdndwuj20s30ra42j.jpg)

**Comment by dzikoysk** [comment] 2018-08-08 09:05
I have no idea. I'm also not sure, that compiled files should be with sources. Could you try to build natives using Xcode?

**Comment by Peng-YM** [comment] 2018-08-09 08:31
I'm not familiar with Xcode, but I tried. It just simply say build failed and give no messages. My Xcode 9 version is much higher than Xcode 5 (used in JCEF official guide).

**Comment by jaredkaczynski** [comment] 2018-10-14 00:17
So, I did some work on it and I think part of the issue is the build script make_distrib.sh for final tar creation has a different path for Mac. I've attached my output jar in any case.

https://drive.google.com/open?id=1yP-mKuE9oxTtkHpl-IL7bEFCnYIghDRE

When the Linux/Windows build finishes it runs these copies:

 ```
cp -f $OUT_BINARY_PATH/chrome-sandbox $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/libjcef.so $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/jcef_helper $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/icudtl.dat $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/libcef.so $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/libEGL.so $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/libGLESv2.so $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/natives_blob.bin $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/snapshot_blob.bin $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/v8_context_snapshot.bin $DISTRIB_LIB_PATH
    cp -f $OUT_BINARY_PATH/*.pak $DISTRIB_LIB_PATH
    cp -rf $OUT_BINARY_PATH/locales/ $DISTRIB_LIB_PATH
    cp -rf $OUT_BINARY_PATH/swiftshader/ $DISTRIB_LIB_PATH
```

But for OSX it ends with:

```
 # Everything else is contained in the app bundle.
    cp -rf $OUT_BINARY_PATH/jcef_app.app $DISTRIB_BIN_PATH
```

And no $DISTRIB_LIB_PATH is set.

So in my case I just copied everything over from the $OUT_BINARY_PATH as the lib folder and ran:

cp -r src/jcef_build/native/Release macosx64/natives

If this is wrong, apologies. The Jar is ~50MB though so I'm assuming it's correct, and at worst just needs to be arranged differently. Otherwise, the jcef_app.app does run properly so at worst case I'm mostly there.

Thanks

**Comment by dzikoysk** [comment] 2018-10-14 10:10
Oh, nice! 

Did you use this build script https://github.com/dzikoysk/Pandomium/wiki/macOS-Build or https://bitbucket.org/chromiumembedded/java-cef/wiki/BranchesAndBuilding?

**Comment by dzikoysk** [comment] 2018-10-14 13:40
Yeah, I'm asking because [macOS-Build](https://github.com/dzikoysk/Pandomium/wiki/macOS-Build) should also create `macosx64/jcef-macosx64.jar`. Could you upload this? I'll add this to the repository :)

I've also took a look on make_distrib.sh before:
![obraz](https://user-images.githubusercontent.com/4235722/46917378-e9ee8f80-cfc6-11e8-9429-3fa472349555.png)
I think I'll also add a patch based on replace to macOS-Build. Unfortunately, I'm not sure how the path should look. You've mention `cp -r src/jcef_build/native/Release macosx64/natives`, `Release macosx64` looks strange for me, I was pretty sure it is `Release`:

![obraz](https://user-images.githubusercontent.com/4235722/46917427-71d49980-cfc7-11e8-99a3-f21a24982f62.png)

**Comment by jaredkaczynski** [comment] 2018-10-14 13:53
So on the build script here:

https://github.com/dzikoysk/Pandomium/blob/master/pandomium-macos/macos-build.sh

Line 57, it's expecting files in ` src/binary_distrib/macosx64/bin/lib/macosx64` But that path is only created and added to in the Linux/Windows build. On the Mac build it stops at the directory `src/jcef_build/native/Release` and doesn't copy the files over.

In any case, here's the output jcef-macosx64.jar

https://drive.google.com/open?id=1K6xeECzYqj6Zk_niNHd5IjlF0hfpSxFV

![image](https://user-images.githubusercontent.com/11617892/46917597-ffe45c00-cf96-11e8-8ca9-aa00f332ed6b.png)

I've also attached an image of the directory structure.

**Comment by dzikoysk** [comment] 2018-10-14 14:16
Thanks 👍 Could you also show me `src/binary_distrib` directory?
![obraz](https://user-images.githubusercontent.com/4235722/46917900-325c7c00-cfcc-11e8-8edf-7e446eba6771.png)

**Comment by dzikoysk** [comment] 2018-10-14 14:44
You can try to launch 67.0.5:

```xml
<dependency>
    <groupId>org.panda-lang</groupId>
    <artifactId>pandomium</artifactId>
    <version>67.0.5</version>
</dependency>
```

**Comment by jaredkaczynski** [comment] 2018-10-14 14:44
Not sure if it's wrong but you uploaded the macosx64-natives.tar, not macosx64-natives.tar.xz.

**Comment by dzikoysk** [comment] 2018-10-14 14:48
Yeah, I was uploading tar.xz while I was writing, should be available now

**Comment by jaredkaczynski** [comment] 2018-10-14 15:15
So, the latest dependency builds have 
`<parent>
    <artifactId>pandomium-parent</artifactId>
    <groupId>org.panda-lang</groupId>
    <version>67.0.5</version>
  </parent>`

In their pom file which results in the error 

> Failed to execute goal on project GhostJavaFX: Could not resolve dependencies for project groupId:GhostJavaFX:jar:1.0-SNAPSHOT: Failed to collect dependencies at org.panda-lang:pandomium:jar:67.0.5: Failed to read artifact descriptor for org.panda-lang:pandomium:jar:67.0.5: Could not find artifact org.panda-lang:pandomium-parent:pom:67.0.5 in panda-repository (https://repo.panda-lang.org)

Could you do a quick explanation of how to use the builds after 67.0.1 with this changed pom file format? 

For now I'll just manually add it though.

**Comment by jaredkaczynski** [comment] 2018-10-14 15:36
I tried doing that and it results in still having that error, and this directory structure:

![image](https://user-images.githubusercontent.com/11617892/46918846-42ad3080-cfa5-11e8-8aab-7371e456c442.png)

![image](https://user-images.githubusercontent.com/11617892/46918854-4e98f280-cfa5-11e8-8b8f-a75f6b0ceed9.png)

**Comment by dzikoysk** [comment] 2018-10-14 15:45
Strange, anyway, try to download this manually: https://repo.panda-lang.org/org/panda-lang/pandomium/67.0.5/pandomium-67.0.5.jar

**Comment by jaredkaczynski** [comment] 2018-10-14 18:06
Okay so I've got IntelliJ running on the VM now. The process hangs on line 74 throwing UnsatisfiedLinkError. I'll do some digging on it.

For Windows the class loads libcef and for Linux it loads cef. Presumably for OSX it should also load libjcef?

https://github.com/dzikoysk/Pandomium/blob/75867b41b11811e31768acb332b176d0b2488247/pandomium-cef/cef/CefApp.java

**Comment by gochev** [comment] 2018-12-17 12:51
Any new information or status update for the mac build ?

**Comment by jaredkaczynski** [comment] 2018-12-19 15:17
It seems like you need things in a .app to use the natives as originally setup. There seems to be a way to modify the natives to not require that but it's pretty confusing.

**Comment by dzikoysk** [comment] 2018-12-19 16:08
I'm not able to prepare the package, this environment is kinda strange and I can't fit it without macOS :/

**Comment by christian-draeger** [comment] 2019-05-07 06:42
hi, just wanted to ask if there is any progress regarding support of MacOS.
just tried to use the maven artifact right now and got this error:
<img width="990" alt="Bildschirmfoto 2019-05-07 um 08 26 30" src="https://user-images.githubusercontent.com/22223458/57276821-f3466300-70a2-11e9-8ea6-f4b41cadc13f.png">
It tries to download the binaries from https://pandomium.panda-lang.org/download/natives/67.0/mac64-natives.tar.xz which points to a dead link.

after having a look at your server https://pandomium.panda-lang.org/download/natives/67.0/macosx64-natives.tar.xz seams to be correct one

**Comment by dzikoysk** [comment] 2019-05-07 11:32
macOS is still not supported. It's strange, closed paltform and I'm not able to work with that platform without buying their hardware.

The url is fixed in https://github.com/dzikoysk/Pandomium/pull/36, but there was not point to merge that if it won't work anyway.

**Comment by kataokaakihisa** [comment] 2019-08-17 17:08
Any updates?

**Comment by johny-coder** [comment] 2019-11-24 01:55
Could be great to see osx support :)

**Comment by rishabhdeepsingh** [comment] 2020-04-17 19:53
@jaredkaczynski which pom.xml was you using?
Any updates?

**Comment by ivanooi** [comment] 2021-06-04 16:17
> Okay so I've got IntelliJ running on the VM now. The process hangs on line 74 throwing UnsatisfiedLinkError. I'll do some digging on it.
> 
> For Windows the class loads libcef and for Linux it loads cef. Presumably for OSX it should also load libjcef?
> 
> The make_binaries script outputs a libjcef.dylib which should be the right file to load. I'm not sure about jcef itself as the only generated file is a .jar.
> 
> https://github.com/dzikoysk/Pandomium/blob/75867b41b11811e31768acb332b176d0b2488247/pandomium-cef/cef/CefApp.java
> 
> [montoyo/mcef#7](https://github.com/montoyo/mcef/issues/7) They did some research on it which saves us some time.
> 
> > I've also read that the following libraries are enough for Mac:
> 
> > ffmpegsoumo.so
> > libcef.dylib (I'm not sure that this is it's correct name)
> > libjcef.dylib
> 
> And it seems ffmpegsoumo is a Chrome native library. I'll await your thoughts though.
> 
> Inside the native zip is the .app as well which contains the large native Chromium Extension Framework file which also might be part of it. You've done more research on this though so maybe you'll have insight.
> 
> Also this post might help on the specifics of what Mac needs.
> 
> https://bitbucket.org/chromiumembedded/java-cef/issues/133/native-libraries-should-be-loaded-manually

Hi , I'm not sure you still have the jcef for Mac 10.9? Thanks

**Comment by dzikoysk** [comment] 2021-06-04 18:50
I kinda gave up, macOS environment is so messed up :< I don't think anyone here successfully launched it there, I think you should just stay with official jcef repository and look for there for a help.

**Comment by rishabhdeepsingh** [comment] 2021-06-04 19:41
I can give it a try If I get to know what to do.

**Comment by dzikoysk** [comment] 2021-06-04 19:50
I don't have time for Pandomium atm anyway due to my other projects. I'll probably get back to this project when I find a need to reuse it and a little clean it up.

**Comment by ivanooi** [comment] 2021-06-05 06:44
> So, I did some work on it and I think part of the issue is the build script make_distrib.sh for final tar creation has a different path for Mac. I've attached my output jar in any case.
> 
> https://drive.google.com/open?id=1yP-mKuE9oxTtkHpl-IL7bEFCnYIghDRE
> 
> When the Linux/Windows build finishes it runs these copies:
> 
> ```
> cp -f $OUT_BINARY_PATH/chrome-sandbox $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/libjcef.so $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/jcef_helper $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/icudtl.dat $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/libcef.so $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/libEGL.so $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/libGLESv2.so $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/natives_blob.bin $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/snapshot_blob.bin $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/v8_context_snapshot.bin $DISTRIB_LIB_PATH
>    cp -f $OUT_BINARY_PATH/*.pak $DISTRIB_LIB_PATH
>    cp -rf $OUT_BINARY_PATH/locales/ $DISTRIB_LIB_PATH
>    cp -rf $OUT_BINARY_PATH/swiftshader/ $DISTRIB_LIB_PATH
> ```
> 
> But for OSX it ends with:
> 
> ```
>  # Everything else is contained in the app bundle.
>     cp -rf $OUT_BINARY_PATH/jcef_app.app $DISTRIB_BIN_PATH
> ```
> 
> And no $DISTRIB_LIB_PATH is set.
> 
> So in my case I just copied everything over from the $OUT_BINARY_PATH as the lib folder and ran:
> 
> cp -r src/jcef_build/native/Release macosx64/natives
> 
> If this is wrong, apologies. The Jar is ~50MB though so I'm assuming it's correct, and at worst just needs to be arranged differently. Otherwise, the jcef_app.app does run properly so at worst case I'm mostly there.
> 
> I compiled it on a Mavericks 10.9 VM without much issue otherwise though.
> 
> Thanks

ok, I just try the jcef on mac 10.9. it work! thanks! :-D

**Comment by dzikoysk** [comment] 2022-04-18 15:16
https://github.com/dzikoysk/pandomium/issues/80#issuecomment-997078418

**Closed by dzikoysk** 2022-04-18 15:16 UTC
Labels: enhancement
